### ISSUE TITLE
2019C的“用出租车GPS数据分析深圳道路交通情况”数据无法下载

### ISSUE THREAD

**Issue by largeword** [Amoiensis/Mathmatic_Modeling_CUMCM#1]
作者你好，2019C的“用出租车GPS数据分析深圳道路交通情况”数据已经无法下载，请问是否可以使用百度网盘共享一下？

**Comment by Amoiensis** [comment]
你好，我已经把CUMCM2019题C的数据上传到百度云了，链接如下。
链接：https://pan.baidu.com/s/1tmysWBUPvd8ef_PrcLAQtg 
提取码：CM19

**Comment by largeword** [comment]
非常感谢

**Comment by renhai-lab** [comment]
你好，链接失效了，能再分享一下吗？感激不尽。👽

**Comment by largeword** [comment]
> 你好，链接失效了，能再分享一下吗？感激不尽。👽

链接: https://pan.baidu.com/s/1-0m0kv5p0G8hu6ksRMF1EA?pwd=hzef 提取码: hzef

**Comment by renhai-lab** [comment]
非常感谢！！！👍👍👍
