### ISSUE TITLE
论文下载不了呢

### ISSUE THREAD

**Issue by newgala22** [Amoiensis/Mathmatic_Modeling_CUMCM#2]
如题

**Comment by Amoiensis** [comment]
你好，论文均在github上了。无法下载，可能是因为网络原因，在大陆Github的下载比较不好用，解决方法如下：
1. 可以在网上查“github文件下载”
2. 在项目主页下载全部内容的压缩文件。

**Comment by newgala22** [comment]
我把vpn打开之后就能下了。不过为啥GitHub上有的文件可以直接下，有的就得开vpn呢
